[build]
  publish = "public"
  command = ""

# Ensure JavaScript files are served with correct MIME type
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000"

# Ensure CSS files are served with correct MIME type
[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"
    Cache-Control = "public, max-age=31536000"

# Ensure HTML files are served with correct MIME type
[[headers]]
  for = "*.html"
  [headers.values]
    Content-Type = "text/html"
    Cache-Control = "public, max-age=3600"

[build.environment]
  NODE_VERSION = "18"

# Security headers for all routes
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"



